on:
  push:
    branches: [ main ]
  pull_request:

name: Continuous integration

jobs:
  ci:
    runs-on: ${{ matrix.runner }}
    strategy:
      matrix:
        runner: [a40]
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          architecture: 'x64'
      - name: Run tests
        run: |
          bash ./ci/run_tests.sh