on:
  push:
    branches: [ main ]
  pull_request:

name: Continuous integration

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v5
        with:
          python-version: '3.13'
          architecture: 'x64'
      - name: Run Script
        run: |
          bash ./ci/script.sh